### ISSUE TITLE
Conversion Leaving blank csv

### ISSUE THREAD

**Issue by Tcby04** [eugeneilyin/nrdtocsv#1]
I appreciate this add on but when I use it gives me a blank CSV
[20230111.csv](https://github.com/eugeneilyin/nrdtocsv/files/10417915/20230111.csv)

**Comment by eugeneilyin** [comment]
Seems like it's an issue with the **Source data**, some **OS** format misleadings (like date/time/currency format inconsistancy with NT generated csv file), or **Storage issues** (write file access, low storage data, etc.).
Try an another test data sources to exclude OS settings reasons.

Unfortunatelly the description or any details of the used internal NT functions are missed.
