### ISSUE TITLE
No L2;2; or L1;2;

### ISSUE THREAD

**Issue by wil70** [eugeneilyin/nrdtocsv#5]
Hello, I noticed I do not see L1;2;* or L2;2;* when I convert to csv?

thanks
w

**Comment by eugeneilyin** [comment]
Check the source files: do they contains the `Last` values? This addon do not filter records, so the issue could be in the absense of `2`  (`Last`) records in the sourced `nrd` files.

**Comment by wil70** [comment]
Thanks @eugeneilyin , effectively I needed to downoad new nrds. Strange they didnt have Last

In the new test I ran with the new nrd, I can see some L1;2;*
I do not see some L2;2;*
Is it expected?

I guess this is ok as that would be redundant with the L1;2;*, isn't it?

thanks
w

**Comment by eugeneilyin** [comment]
IDK what is in that nrd's, anyways this is just a converted, no filter functionality is applied inside.
